
//IDs for add buttons
#define ID_ADD_BEAM 101
#define ID_ADD_FORCE_Y 102
#define ID_ADD_FORCE_X 103
#define ID_ADD_MOMENT 104
#define ID_ADD_UNIFORM_LOAD 105
#define ID_CALCULATE 213


//IDs for edit fields
#define IDC_EDIT_BEAM 201
#define IDC_EDIT_FORCE_Y 202
#define IDC_EDIT_FORCE_Y_POSITION 203
#define IDC_EDIT_FORCE_X 204
#define IDC_EDIT_FORCE_X_POSITION 205
#define IDC_EDIT_MOMENT 206
#define IDC_EDIT_MOMENT_POSITION 207
#define IDC_EDIT_UNIFORM_LOAD 208
#define IDC_EDIT_UNIFORM_LOAD_X1_POSITION 209
#define IDC_EDIT_UNIFORM_LOAD_X2_POSITION 210
#define IDC_FILE_EXIT	211
#define IDC_HELP_ABOUT	212
#define IDC_RESULT_A_FY 214
#define IDC_RESULT_A_FX 215
#define IDC_RESULT_B_FY 216
#define IDC_RESULT_MAX_MOMENT 217







